[package]
name = "yumlabs-twitch"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
reqwest = "0.12.9"
serde_json = "1.0.132"
tokio = "1.41.0"
twitch_comment_stream = "0.1.0"
